### ISSUE TITLE
Admin plugin error

### ISSUE THREAD

**Issue by emersonveenstra** [emersonveenstra/vbot#42]
```
TypeError: Cannot read property 'indexOf' of undefined
    at Admin.parseCommand (/home/vbot/vbot/plugins/admin/index.js:6:35)
    at Bot.parse_message (/home/vbot/vbot/vbot.js:112:45)
    at Bot.receive_data (/home/vbot/vbot/vbot.js:209:26)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:109:10)
    at TLSWrap.onread (net.js:517:20)
```

**Comment by emersonveenstra** [comment]
Fixed
